eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

#feign集成了Hystrix,启用
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true  //使用okHttp作为Http请求API
    #请求与响应压缩
  compression:
    request:
      mime-types: text/xml,application/xml,application/json   #压缩的请求类型
      min-request-size: 2048  #请求超过指定大小才压缩
      enabled: true
    response:
      enabled: true


#开启feign客户端的DEBUG日志
logging:
  level:
    com:
      jk51:
        feignInterface:
          HelloService: DEBUG