eureka:
  client:
    service-url:
      defaultZone: http://192.168.175.129:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

#feign集成了Hystrix,启用
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true