spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      #uri: http://localhost:8888/  在使用服务化配置中心时不需要配置config server的URI
      discovery:
        enabled: true
        service-id: config-server
      #username: user   #config server srcurity账户密码
      #password: 37cc5635-559b-4e6f-b633-7e932b813f73
server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




