spring:
  application:
    name: config-client
  cloud:
    config:
      profile: dev
      label: master
      #uri: http://localhost:8888/  在使用服务化配置中心时不需要配置config server的URI
      discovery:
        enabled: true
        service-id: config-server
    bus:
      trace:
        enabled: true   #开启消息跟踪
  rabbitmq:  #spring cloud bus rabbitmq 配置
    host: localhost
    port: 5672
    username: test
    password: 123456

server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#关闭安全验证
management:
  security:
    enabled: false

