eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/     #指定服务注册中心的地址
    healthcheck:
      enabled: true
  instance:   #eureka服务注册列表默认显示主机名+端口号，以下的设置使其显示IP+端口号
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8762
spring:
  application:
    name: service-hi    #服务名称，
  #整合zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
      sampler:
        percentage: 1  #抽样收集，在测试的时候100%收集
management:
  security:
    enabled: false
