spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jay20160803/spring-cloud-config.git  #配置git仓库地址
          search-paths: respo                                          #配置仓库路径下的相对搜索地址，可以配置多个
          username:             #访问Git仓库的用户名
          password:             #访问Git仓库的用户密码
      label: master             #git项目分支

server:
 port: 8888


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#配置spring security 用户名密码
#security:
 # user:
 #   name: user
 #   password: 37cc5635-559b-4e6f-b633-7e932b813f73


