eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: service-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true   #开启Ribbon重试机制----还需要导入spring-retry包

service-hi:
  ribbon:
     ReadTimeout: 1000
     ConnectTimeout: 250
     OkToRetryOnAllOperations: true  #对所有操作请求都进行重试
     MaxAutoRetriesNextServer: 2     #切换实例的重试次数
     MaxAutoRetrie: 1                #对当前实例的重试次数





#Hystrix设置
hystrix:
  threadpool:
    defult:  #HystrixCommandKey  设置某个服务实例的Hytrix设置，如果需要设置在所有的实例上都生效（改成"default"）
      coreSize: 30
      maxQueueSize: 30
      queueSizeRejectionThreshold: 30
  command:
    defult: #HystrixCommandKey（表示某个实例）
      execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000